### PR TITLE
handle sha256 for zero-length file without using remote cache

### PR DESCRIPTION
**Pull request by mpictor**
I'm using [`bazel-remote`](https://github.com/buchgr/bazel-remote) for AC and small CAS. It refuses to cache anything without a `Content-Length` header, leading to errors:

```no-highlight
2018/10/23 23:26:47 PUT without Content-Length (key = cas/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
2018/10/23 23:26:47  GET 404    10.25.188.34 /cas/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

The documentation for http.Request's ContentLength field ([link](https://golang.org/pkg/net/http/#Request)) indicates that a Content-Length of 0 is treated as unknown by the client:
```golang
        /* ... */
        // For client requests, a value of 0 with a non-nil Body is
        // also treated as unknown.
        ContentLength int64
```

This PR works around the problem by checking for the zero-length hash and handling it locally, returning success for `Put()`, a zero-length buffer for `Get()`, and skipping it in the case of `FindMissing()`.

### CODE REVIEW

**Comment by mpictor** [comment]
I discussed this some [on slack](https://buildteamworld.slack.com/messages/CD6HZC750/?) but you haven't been on there :)

**Comment by EdSchouten** [comment]
Hi Mark,

Thanks for the patch! Instead of solving this by extending remoteBlobAccess, what are your thoughts on solving it a bit higher in the stack? In the `empty-blob-filtering` branch I've added a new adapter to filter out empty blobs entirely. Could you give that a try and let me know what you think? Thanks!

**Comment by mpictor** [comment]
Sure, I'll give that a try!

**Comment by EdSchouten** [comment]
Hmmm... Reading the documentation of the Go HTTP library, I think we can also solve this a bit simpler by using `http.NoBody` in this case. Can you give the `remote-put-zero` branch a try as well? If that works, I'd be equally happy to merge that, as it keeps the code simple.

**Comment by EdSchouten** [comment]
What was the actual conclusion on this? Did the code in the `empty-blob-filtering` and `remote-put-zero` branches work?

**Pull request closed without merging**
